version: '3.7'

services:
  service:
    image: asset_api
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    ports:
      - "8881:8000"
    depends_on:
      - app_db
    networks:
      - base-network


networks:
  base-network:
    external: true
